title: Imran Aliyev # your name (or website title) here
logo: "/My-portfolio/images
/imran photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This Power BI project visualizes the impact of COVID-19 in Poland by analyzing key metrics such as deaths, new deaths, new recoveries, and total recoveries. The dashboard presents:

118K total deaths, 1,676 new deaths, and 1M recovered cases as of the latest data point.
A line chart tracks the progression of the pandemic over the year, highlighting important monthly trends in deaths, new cases, and recoveries. For example, in March, there were 213 deaths, 33 new deaths, and 94 recoveries, showing the pandemic's intensity during that period.
The dashboard enables users to filter data by time period (year, quarter, or month) to gain deeper insights into the spread and recovery patterns of COVID-19 in Poland. By using dynamic visuals and interactive elements, this analysis helps communicate the pandemic's ongoing effects in an easily digestible format for decision-makers and the general public.  from this text change this sentence to a better Through dynamic visuals and interactive elements, this analysis effectively conveys the ongoing impact of the pandemic in a clear and accessible format, facilitating informed decision-making for policymakers and enhancing public understanding.  
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
